name: template-checker

on:
  push:
    branches:
      - main
      - cl/JuoCode/check-workflow

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          result-encoding: string
          retries: 3
          retry-exempt-status-codes: 400,401
          script: |
            const { owner, repo } = context.repo;
            const statusToFind = 'success'; // Replace with the desired status (e.g., 'success', 'failure', 'pending')
            const perPage = 100; // Number of commits to fetch per page
            let page = 1;
            let commitWithStatus = null;

            while (!commitWithStatus) {
              const commits = await github.repos.listCommits({
                owner,
                repo,
                per_page: perPage,
                page: page
              });
              for (const commit of commits.data) {
                const { data: statuses } = await github.repos.listCommitStatusesForRef({
                  owner,
                  repo,
                  ref: commit.sha
                });
                if (statuses.some(status => status.state === statusToFind)) {
                  commitWithStatus = commit;
                  break;
                }
              }
              if (commits.data.length < perPage) {
                break; // No more commits to fetch
              }
              page++;
            }

            if (commitWithStatus) {
              console.log(`Found commit: ${commitWithStatus.sha} with status: ${statusToFind}`);
              core.setOutput('commit_sha', commitWithStatus.sha);
            } else {
              console.log(`No commit found with status: ${statusToFind}`);
              core.setOutput('commit_sha', '');
            }
